ExampleWebApp/BobWebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ExampleWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ExampleWebApp/BobWebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WestWindSystem.BLL;
using WestWindSystem.Entities;

namespace ExampleWebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly BuildVersionServices _buildVersionServices;

        public IndexModel(ILogger<IndexModel> logger, BuildVersionServices buildVersionServices)
        {
            _logger = logger;
            _buildVersionServices = buildVersionServices;
        }

        [TempData]
        public string MyName { get; set; }

        public BuildVersion BuildVersionInfo { get; set; }

        [TempData]
        public string IndexFeedback { get; set; }

        [BindProperty(SupportsGet = true)]
        public int number { get; set; }

        public void OnGet()
        {
            Random random = new Random();
            int value = random.Next(0, 100);

            if (value % 2 == 0)
            {
                MyName = $"To CPSC 1517 - Razor World! ({value})";
            }
            else
            {
                MyName = null;
            }

            BuildVersionInfo = _buildVersionServices.GetBuildVersion();
        }

        public IActionResult OnPostAButton()
        {
            string buttonValue = Request.Form["theButton"];
            IndexFeedback = $"The A handler button was pressed and the value was: {number}";
            return RedirectToPage(new { number = number });
        }

        public IActionResult OnPostBButton()
        {
            string buttonValue = Request.Form["theButton"];
            IndexFeedback = $"The B handler button was pressed and the value was: {number}";
            return RedirectToPage(new { number = number });
        }  
    }
}

ExampleWebApp/BobWebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExampleWebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ExampleWebApp/BobWebApp/Pages/Regions.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WestWindSystem.BLL;
using WestWindSystem.Entities;

namespace ExampleWebApp.Pages
{
    public class RegionsModel : PageModel
    {
        #region Private services fields and class constructor
        private readonly ILogger<RegionsModel> _logger;
        private readonly RegionServices _regionServices;
        
        public RegionsModel(ILogger<RegionsModel> logger, RegionServices regionServices)
        {
            _logger = logger;
            _regionServices = regionServices;
        }
        #endregion

        [TempData]
        public string FeedbackMessage { get; set; }

        //BindProperty is bond to the asp-for help tag
        //Adding SupportGet = true will allow this property to be match to
        //a routing parameter of the same name.
        [BindProperty(SupportsGet = true)]
        public int regionID { get; set; }

        public List<Region> RegionList { get; set; }

        [BindProperty(SupportsGet = true)]
        public int selectedRegionID { get; set; }
        public Region regionInfo { get; set; }
        public void OnGet()
        {
            //Check first for region id > 0
            if (regionID > 0)
            {
                //Region is greater than 0
                if (regionID <= 0)
                {
                    //If not gt0 then -> Tell the user they must provide a positive whole number
                    FeedbackMessage = "Region ID must be a positive non-zero number.";
                }
                else
                {
                    //If it is gt0 -> Query for the region
                    regionInfo = _regionServices.Region_GetById(regionID);

                    //Check if the return is a null
                    if (regionInfo == null)
                    {
                        //If the return is a null -> Tell the user the region id was not valid.
                        FeedbackMessage = "Region ID is not valid. No region exists with the supplied ID.";
                    }
                    else
                    {
                        //If the return is not null -> Tell the user the region id and region description!
                        FeedbackMessage = $"ID: {regionInfo.RegionID} Description: {regionInfo.RegionDescription}";
                    }
                }
            }
            RegionList = _regionServices.Region_List();
        }

        public void OnPost()
        {
            FeedbackMessage = "WARNING!!! No OnPost page handler found. Execution defaulted to the coded OnPost()";
        }

        public IActionResult OnPostFetch()
        {
            if (regionID < 1)
            {
                FeedbackMessage = "Region ID must be a positive non-zero number.";
            }
                return RedirectToPage(new { regionID = regionID });
        }

        public IActionResult OnPostClear()
        {
            FeedbackMessage = "";
            //regionID = 0;
            ModelState.Clear();
            return RedirectToPage(new {regionID = (int?)null});
        }
    }
}

ExampleWebApp/BobWebApp/Pages/Samples/Regions.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional Namespaces
using WestWindSystem.BLL;
using WestWindSystem.Entities;
#endregion

namespace ExampleWebApp.Pages
{
    public class RegionsModel : PageModel
    {
        #region Private services fields and class constructor
        private readonly ILogger<RegionsModel> _logger;
        private readonly RegionServices _regionServices;
        
        public RegionsModel(ILogger<RegionsModel> logger, RegionServices regionServices)
        {
            _logger = logger;
            _regionServices = regionServices;
        }
        #endregion

        [TempData]
        public string RegionFeedback { get; set; }

        //BindProperty is bond to the asp-for help tag
        //Adding SupportGet = true will allow this property to be match to
        //a routing parameter of the same name.
        [BindProperty(SupportsGet = true)]
        public int regionID { get; set; }

        public List<Region> RegionList { get; set; }

        [BindProperty(SupportsGet = true)]
        public int selectedRegionID { get; set; }
        public Region regionInfo { get; set; }
        public void OnGet()
        {
            //Check first for region id > 0
            if (regionID > 0)
            {
                //Region is greater than 0
                if (regionID <= 0)
                {
                    //If not gt0 then -> Tell the user they must provide a positive whole number
                    RegionFeedback = "Region ID must be a positive non-zero number.";
                }
                else
                {
                    //If it is gt0 -> Query for the region
                    regionInfo = _regionServices.Region_GetById(regionID);

                    //Check if the return is a null
                    if (regionInfo == null)
                    {
                        //If the return is a null -> Tell the user the region id was not valid.
                        RegionFeedback = "Region ID is not valid. No region exists with the supplied ID.";
                    }
                    else
                    {
                        //If the return is not null -> Tell the user the region id and region description!
                        RegionFeedback = $"ID: {regionInfo.RegionID} Description: {regionInfo.RegionDescription}";
                    }
                }
            }
            RegionList = _regionServices.Region_List();
        }

        public void OnPost()
        {
            RegionFeedback = "WARNING!!! No OnPost page handler found. Execution defaulted to the coded OnPost()";
        }

        public IActionResult OnPostFetch()
        {
            if (regionID < 1)
            {
                RegionFeedback = "Required: Region ID must be a positive non-zero number.";
            }
            return RedirectToPage(new { regionID = regionID });
        }

        public IActionResult OnPostBySelection()
        {
            if (regionID < 1)
            {
                RegionFeedback = "Required: Select a region to view.";
            }
            return RedirectToPage(new { regionID = selectedRegionID });
        }

        public IActionResult OnPostClear()
        {
            RegionFeedback = "";
            //regionID = 0;
            ModelState.Clear();
            return RedirectToPage(new {regionID = (int?)null});
        }
    }
}

ExampleWebApp/BobWebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    @if (string.IsNullOrWhiteSpace(Model.MyName))
    {
        <p>The world of Razor is currently closed :(</p>
    }
    else
    {
        <p>@Model.MyName</p>
    }
    <br/>
    @if (Model.BuildVersionInfo == null)
    {
        <p style="font-weight:bold;">Build Version Unknown</p>
    }
    else
    {
        <p>Database Version: @Model.BuildVersionInfo.Major . 
                             @Model.BuildVersionInfo.Minor .
                             @Model.BuildVersionInfo.Build
            was released on @Model.BuildVersionInfo.ReleaseDate.ToShortDateString()
        </p>
    }
</div>

<!--
    helper tag: asp-for
        the tag tie the control (the input or any other control) 
        to the data in our Model ("code-behind") Class
-->

<form method="post">
    <label>
        Enter a number: <input type="number" asp-for="number"/>
    </label>
    <br/>
    <button type="submit" value="A Button" class="btn btn-success" id="theButton" 
        name="theButton" asp-page-handler="AButton">A Button</button>
    &nbsp;&nbsp;
    <button type="submit" value="B Button" class="btn btn-warning" id="theButton" 
        name="theButton" asp-page-handler="BButton">B Button</button>
    <br/>
    <p class="text-danger bold">@Model.IndexFeedback</p>
</form>

ExampleWebApp/BobWebApp/Pages/Regions.cshtml
@page
@model ExampleWebApp.Pages.RegionsModel
@{
	ViewData["Title"] = "Region Queries";
}
<h1>Region Queries</h1>

<p>@Model.FeedbackMessage</p>

<form method="post">
	<label>
		@*
			the type of attribute for input can be set to different types for acceptable values
			"number" restricts the input to numericals
			the numerics by default are whole numbers
			but they can be negative or positive numbers

			We can define different attributes to refine the acceptable values
			min="xxx" indicates the minimum acceptable value
			max="xxx" indicates the maximum acceptable value
			step="xxx" indicates the increments of the acceptable values
				step="1" (default) this indicates only whole numbers are accepted
				step="0.01" this indicates decimals are accepted in increments of .01
					(this is great for $ amounts)
			required indicate that the field must have a value

			When you use validation attributes on your form input controls
				the user MUST meet the validation BEFORE the form is sent to the
				web server for processing

			To not cause validation to happen, add the attribute formnovalidate to the button. 
				formnovalidate overrides any validation (html5) that exists in any form control.
		*@
		Enter Region ID:
		<input type="number" asp-for="regionID"
			placeholder="enter your region id number" 
			required/>
	</label>
	<br />
	<button type="submit" asp-page-handler="Fetch">Fetch By ID</button>
	<button type="submit" asp-page-handler="Clear" formnovalidate>Clear</button>
	<br />
	<br />
	<label>
		Select a Region:
		<select asp-for="selectedRegionID">
			<option value="0">select...</option>
			@foreach(var region in Model.RegionList)
			{
				<option value="@region.RegionID">@region.RegionDescription</option>
			}
		</select>
	</label>
	<button type="submit" asp-page-handler="BySelection">Fetch Selected Region</button>

</form>