ExampleWebApp/BobWebApp/Pages/Regions.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WestWindSystem.BLL;
using WestWindSystem.Entities;

namespace ExampleWebApp.Pages
{
    public class RegionsModel : PageModel
    {
        #region Private services fields and class constructor
        private readonly ILogger<RegionsModel> _logger;
        private readonly RegionServices _regionServices;
        
        public RegionsModel(ILogger<RegionsModel> logger, RegionServices regionServices)
        {
            _logger = logger;
            _regionServices = regionServices;
        }
        #endregion

        [TempData]
        public string FeedbackMessage { get; set; }

        //BindProperty is bond to the asp-for help tag
        //Adding SupportGet = true will allow this property to be match to
        //a routing parameter of the same name.
        [BindProperty(SupportsGet = true)]
        public int regionID { get; set; }

        public List<Region> RegionList { get; set; }

        [BindProperty(SupportsGet = true)]
        public int selectedRegionID { get; set; }
        public Region regionInfo { get; set; }
        public void OnGet()
        {
            //Check first for region id > 0
            if (regionID > 0)
            {
                //Region is greater than 0
                if (regionID <= 0)
                {
                    //If not gt0 then -> Tell the user they must provide a positive whole number
                    FeedbackMessage = "Region ID must be a positive non-zero number.";
                }
                else
                {
                    //If it is gt0 -> Query for the region
                    regionInfo = _regionServices.Region_GetById(regionID);

                    //Check if the return is a null
                    if (regionInfo == null)
                    {
                        //If the return is a null -> Tell the user the region id was not valid.
                        FeedbackMessage = "Region ID is not valid. No region exists with the supplied ID.";
                    }
                    else
                    {
                        //If the return is not null -> Tell the user the region id and region description!
                        FeedbackMessage = $"ID: {regionInfo.RegionID} Description: {regionInfo.RegionDescription}";
                    }
                }
            }
            RegionList = _regionServices.Region_List();
        }

        public void OnPost()
        {
            FeedbackMessage = "WARNING!!! No OnPost page handler found. Execution defaulted to the coded OnPost()";
        }

        public IActionResult OnPostFetch()
        {
            if (regionID < 1)
            {
                FeedbackMessage = "Region ID must be a positive non-zero number.";
            }
                return RedirectToPage(new { regionID = regionID });
        }

        public IActionResult OnPostClear()
        {
            FeedbackMessage = "";
            //regionID = 0;
            ModelState.Clear();
            return RedirectToPage(new {regionID = (int?)null});
        }
    }
}

ExampleWebApp/BobWebApp/Pages/Samples/CategoryProducts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional Namespaces
using WestWindSystem.BLL;
using WestWindSystem.Entities;
using WebApp.Helpers;
#endregion

namespace ExampleWebApp.Pages.Samples
{
    public class CategoryProductsModel : PageModel
    {
        #region Private services fields and class constructor
        private readonly ILogger<OrdersModel> _logger;
        private readonly CategoryServices _categoryServices;
        private readonly ProductServices _productServices;
        private readonly SupplierServices _supplierServices;

        public CategoryProductsModel(ILogger<OrdersModel> logger, CategoryServices categoryServices, ProductServices productServices, SupplierServices supplierServices)
        {
            _logger = logger;
            _categoryServices = categoryServices;
            _productServices = productServices;
            _supplierServices = supplierServices;
        }
        #endregion

        [TempData]
        public string Feedback { get; set; }

        [BindProperty(SupportsGet =true)]
        public int searchCatagoryID { get; set; }

        public List<Product> ProductInfo { get; set; }

        [BindProperty]
        public List<Category> CategoryList { get; set; } = new();

        [BindProperty]
        public List<Supplier> SupplierList { get; set; } = new();
        public void OnGet()
        {
            PopulateLists();
            if(searchCatagoryID != 0)
            {
                ProductInfo = _productServices.Product_CategoryProducts(searchCatagoryID);
            }
        }

        private void PopulateLists()
        {
            CategoryList = _categoryServices.Category_List();
            SupplierList = _supplierServices.Supplier_List();
        }

        public IActionResult OnPostFetch()
        {
            if(searchCatagoryID == 0)
            {
                Feedback = "Required: Search category not selected.";
            }

            return RedirectToPage(new { searchCatagoryID = searchCatagoryID });
        }

        public IActionResult OnPostClear()
        {
            Feedback = "";
            ModelState.Clear();
            return RedirectToPage(new { searchCatagoryID = (int?)null });
        }

        public IActionResult OnPostNew()
        {
            return RedirectToPage("/Samples/ProductCRUD");
        }
    }
}

ExampleWebApp/BobWebApp/Pages/Samples/Orders.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional Namespaces
using WestWindSystem.BLL;
using WestWindSystem.Entities;
using WebApp.Helpers;
#endregion

namespace ExampleWebApp.Pages.Samples
{
    public class OrdersModel : PageModel
    {
        #region Private services fields and class constructor
        private readonly ILogger<OrdersModel> _logger;
        private readonly OrderServices _orderServices;
        private readonly CustomerServices _customerServices;

        public OrdersModel(ILogger<OrdersModel> logger, OrderServices orderServices, CustomerServices customerServices)
        {
            _logger = logger;
            _orderServices = orderServices;
            _customerServices = customerServices;
        }
        #endregion

        #region Paginator
        //set the desired page size
        private const int PAGE_SIZE = 5;
        //be able to hold an instance of the Paginator Class
        public Paginator Pager { get; set; }
        #endregion

        [TempData]
        public string orderFeedback { get; set; }

        public List<Order> OrderResults { get; set; } = new List<Order>();

        [BindProperty(SupportsGet = true)]
        public string searchCustomerID { get; set; }

        public List<Customer> CustomerList { get; set; } = new List<Customer>();

        public void OnGet(int? currentPage)
        {
            CustomerList = _customerServices.Customer_List();

            if (!string.IsNullOrEmpty(searchCustomerID))
            {
                int totalCount;
                int pageNumber = currentPage.HasValue ? currentPage.Value : 1;
                PageState current = new(pageNumber, PAGE_SIZE);
                OrderResults = _orderServices.GetOrderByCustomerID(searchCustomerID, pageNumber, PAGE_SIZE, out totalCount);
                Pager = new Paginator(totalCount, current);
            }
            
        }

        public IActionResult OnPostDDLSearch()
        {
            if (string.IsNullOrEmpty(searchCustomerID))
            {
                orderFeedback = "Required: Must select a Customer.";
            }
            return RedirectToPage(new { searchCustomerID = searchCustomerID });
        }
    }
}

ExampleWebApp/BobWebApp/Pages/Samples/PartialFilterSearch.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional Namespaces
using WestWindSystem.BLL;
using WestWindSystem.Entities;
using WebApp.Helpers;
#endregion

namespace ExampleWebApp.Pages.Samples
{
    public class PartialFilterSearchModel : PageModel
    {
        #region Private services fields and class constructor
        private readonly ILogger<PartialFilterSearchModel> _logger;
        private readonly TerritoryServices _territoryServices;

        public PartialFilterSearchModel(ILogger<PartialFilterSearchModel> logger, TerritoryServices territoryServices)
        {
            _logger = logger;
            _territoryServices = territoryServices;
        }
        #endregion

        [TempData]
        public string partialSearchFeedback { get; set; }

        [BindProperty(SupportsGet = true)]
        public string partialSearchText { get; set; }

        public List<Territory> TerritoryResults { get; set; } = new List<Territory>();

        #region Paginator
        //set the desired page size
        private const int PAGE_SIZE = 5;
        //be able to hold an instance of the Paginator Class
        public Paginator Pager { get; set; }
        #endregion

        public void OnGet(int? currentPage)
        {

            //using the Paginator with your query

            //OnGet ends up with a parameter (Request query string) that receives the current
            // page number. On the initial load of the page, this value will be null
            // to be null we had to add the ? after int.
            if(!string.IsNullOrEmpty(partialSearchText))
			{
                //temp value for the number of results for our query
                int totalCount;
                //set up for using the paginator if a query is run, no need if no query

                // determine the current page number

                int pageNumber = currentPage.HasValue ? currentPage.Value : 1;
                //set up the current state of the paginator (with the sizing)
                PageState current = new(pageNumber, PAGE_SIZE);
                //do our query
                TerritoryResults = _territoryServices.GetByPartialDescription(partialSearchText, pageNumber, PAGE_SIZE, out totalCount);

                Pager = new Paginator(totalCount, current);
			}
        }

        public IActionResult OnPostSearch()
        {
            if (string.IsNullOrEmpty(partialSearchText))
            {
                partialSearchFeedback = "Required: Search string is empty.";
            }

            return RedirectToPage(new { partialSearchText = partialSearchText });
        }

        public IActionResult OnPostClear()
        {
            partialSearchFeedback = "";
            ModelState.Clear();
            return RedirectToPage(new { PartialSearchText = (string?)null });
        }
    }
}

ExampleWebApp/BobWebApp/Pages/Samples/ProductCRUD.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional Namespaces
using WestWindSystem.BLL;
using WestWindSystem.Entities;
using WebApp.Helpers;
#endregion

namespace ExampleWebApp.Pages.Samples
{
    public class ProductCRUDModel : PageModel
    {
        #region Private services fields and class constructor
        private readonly ILogger<OrdersModel> _logger;
        private readonly CategoryServices _categoryServices;
        private readonly ProductServices _productServices;
        private readonly SupplierServices _supplierServices;

        public ProductCRUDModel(ILogger<OrdersModel> logger, CategoryServices categoryServices, ProductServices productServices, SupplierServices supplierServices)
        {
            _logger = logger;
            _categoryServices = categoryServices;
            _productServices = productServices;
            _supplierServices = supplierServices;
        }
        #endregion

        #region Feedback and Error Messages

        [TempData]
        public string Feedback { get; set; }

        public bool HasFeedback => !string.IsNullOrWhiteSpace(Feedback);

        [TempData]
        public string ErrorMessage { get; set; }

        public bool HasError => !string.IsNullOrWhiteSpace(ErrorMessage);

        #endregion
        [BindProperty(SupportsGet = true)]
        public int? productID { get; set; }

        [BindProperty]
        public Product ProductInfo { get; set; }

        [BindProperty]
        public List<Category> CategoryList { get; set; }

        [BindProperty]
        public List<Supplier> SupplierList { get; set; }


        public void OnGet()
        {
            PopulateLists();
            if(productID.HasValue && productID > 0)
            {
                ProductInfo = _productServices.Product_GetByID(productID.Value);
            }
        }
        private void PopulateLists()
        {
            CategoryList = _categoryServices.Category_List();
            SupplierList = _supplierServices.Supplier_List();
        }

        public IActionResult OnPostClear()
        {
            Feedback = "";
            ModelState.Clear();
            return RedirectToPage(new { productid = (int?)null });
        }

        public IActionResult OnPostSearch()
        {
            return RedirectToPage("/Samples/CategoryProducts");
        }

        public IActionResult OnPostNew()
        {
            if(ModelState.IsValid)
            {
                //We will always do new with user friendly error handling
                try
                {
                    //call the appropriate service to try and add the new record
                    int productNew = _productServices.Product_AddProduct(ProductInfo);
                    Feedback = "Product was added.";
                    return RedirectToPage(new { productID = productNew });
                }
                catch (Exception ex)
                {
                    Feedback = GetInnerException(ex);
                    PopulateLists();
                    return Page();
                }
            }
            else
            {
                PopulateLists();
                return Page();
            }
        }

        public IActionResult OnPostUpdate()
        {
            if (ModelState.IsValid)
            {
                //We will always do new with user friendly error handling
                try
                {
                    //call the appropriate service to try and update the record
                    int updated = _productServices.Product_UpdateProduct(ProductInfo);
                    Feedback = $"{updated} product(s) were updated.";
                    return RedirectToPage(new { productID = ProductInfo.ProductID });
                }
                catch (Exception ex)
                {
                    Feedback = GetInnerException(ex);
                    PopulateLists();
                    return Page();
                }
            }
            else
            {
                PopulateLists();
                return Page();
            }
        }

        public IActionResult OnPostDelete()
        {
            if (ModelState.IsValid)
            {
                //We will always do new with user friendly error handling
                try
                {
                    //call the appropriate service to try and update the record
                    int deleted = _productServices.Product_DeleteProduct(ProductInfo);
                    Feedback = $"{deleted} product(s) were discontinued.";
                    return RedirectToPage(new { productID = ProductInfo.ProductID });
                }
                catch (Exception ex)
                {
                    Feedback = GetInnerException(ex);
                    PopulateLists();
                    return Page();
                }
            }
            else
            {
                PopulateLists();
                return Page();
            }
        }

        private string GetInnerException(Exception ex)
        {
            while(ex.InnerException != null)
            {
                ex = ex.InnerException;
            }
            return ex.Message;
        }
    }
}

ExampleWebApp/BobWebApp/Pages/Samples/ReceivingPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional Namespaces
using WestWindSystem.BLL;
using WestWindSystem.Entities;
using WebApp.Helpers;
#endregion

namespace ExampleWebApp.Pages.Samples
{
    public class ReceivingPageModel : PageModel
    {
        #region Private services fields and class constructor
        private readonly ILogger<ReceivingPageModel> _logger;
        private readonly TerritoryServices _territoryServices;
        private readonly RegionServices _regionServices;

        public ReceivingPageModel(ILogger<ReceivingPageModel> logger, TerritoryServices territoryServices, RegionServices regionServices)
        {
            _logger = logger;
            _territoryServices = territoryServices;
            _regionServices = regionServices;
        }
        #endregion

        [BindProperty(SupportsGet = true)]
        public string? territoryID { get; set; }

        public string territoryDescription { get; set; }

        public int regionID { get; set; }

        public List<Region> regionsList { get; set; }
        public void OnGet()
        {
            if(!string.IsNullOrEmpty(territoryID))
            {
                Territory territory = _territoryServices.GetTerritoryByID(territoryID);
                territoryDescription = territory.TerritoryDescription;
                regionID = territory.RegionID;
                regionsList = _regionServices.Region_List();
            }
        }
    }
}

ExampleWebApp/BobWebApp/Pages/Samples/CategoryProducts.cshtml
@page
@model ExampleWebApp.Pages.Samples.CategoryProductsModel
@{
	ViewData["Title"] = "Category Products";
}

<h1>Category Products: Select a Product for Maintenance</h1>

<p>@Model.Feedback</p>

<form method="post">
	<label>
		Select a Category:
		<select asp-for="searchCatagoryID">
            <option value="0">select ...</option>
            @foreach (var cat in Model.CategoryList)
            {
                <option value="@cat.CategoryID" selected=@(cat.CategoryID == Model.searchCatagoryID )>
                    @cat.CategoryName
                </option>
            }
        </select>
	</label>
    <br/>
    @*restrict the display of the table to when there is data to view*@
    @if (Model.ProductInfo != null)
    {
        if (Model.ProductInfo.Count == 0)
        {
            <p style="color:blueviolet; font-weight:bold; font-size:large;">
                There are no products matching your search request.
            </p>
        }
        else
        {
            <table>
                <thead>
                    @*used for column titles*@
                    <tr>
                        <th></th>
                        <th>Product</th>
                        <th>Supplier</th>
                        <th>Unit Size</th>
                        <th>Disc</th>
                    </tr>
                </thead>
                <tbody>
                    
                    @foreach (var item in Model.ProductInfo)
                    {
                        
                        <tr>
                            <td>
                                <a href="/Samples/ProductCRUD/@item.ProductID">
                                    Edit
                                </a>
                            </td>
                            <td>@item.ProductName</td>
                            <td><select disabled="true">
                                    @foreach (var supplier in Model.SupplierList)
                                    {
                                        if (supplier.SupplierID == item.SupplierID)
                                        {
                                            <option value="@supplier.SupplierID" selected>@supplier.CompanyName</option>
                                        }
                                        else
                                        {
                                            <option value="@supplier.SupplierID">@supplier.CompanyName</option>
                                        }
                                    }
                                </select> 
                            </td>
                            <td>@item.QuantityPerUnit</td>
                            <td>
                                <input type="checkbox" checked="@item.Discontinued">
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                
                </tfoot>
            </table>
        }
    }
    <button type="submit" asp-page-handler="Fetch">Fetch Products</button>&nbsp;&nbsp;
    <button type="submit" asp-page-handler="Clear" formnovalidate>Clear</button>&nbsp;&nbsp;
    <button type="submit" asp-page-handler="New" formnovalidate>New Product</button>
</form>

ExampleWebApp/BobWebApp/Pages/Samples/PartialFilterSearch.cshtml
@page 
@model ExampleWebApp.Pages.Samples.PartialFilterSearchModel
@{
	ViewData["Title"] = "Partial String Table Queries";
}

<h1>Partial String Query Resulting in a Table Display</h1>

<p>@Model.partialSearchFeedback</p>

<form method="post">
	<label>
		Enter a partial Territory description:
		<input type="text" asp-for="partialSearchText"
			placeholder="enter your search string" />
	</label>
	<button type="submit" asp-page-handler="Search">Search Territories</button>
	<br />
	<select asp-for="searchRegionID">
		<option value="0">select a region...</option>
		@foreach(var region in Model.RegionsList)
		{
		
			if(region.RegionID == Model.searchRegionID)
			{
				<option value="@region.RegionID" selected>@region.RegionDescription</option>
			}
			else
			{
				<option value="@region.RegionID">@region.RegionDescription</option>
			}
		}
	</select>
	<button type="submit" asp-page-handler="DDLSearch">Search Territories</button>
	<br />
	@if (!string.IsNullOrEmpty(Model.partialSearchText) || Model.searchRegionID >= 1)
	{
		if (Model.TerritoryResults.Count == 0)
		{
			<p style="color:deeppink; font-weight:bold; font-size:large;">
				There are no territories matching your search request.
			</p>
		}
		else 
		{
			<table>
				<thead>
					@*Used for the column titles*@
					<tr>
						<th>Territory ID</th>
						<th>Description</th>
						<th>Region ID</th>
					</tr>
				</thead>
				<tbody>
					@*Used for the table rows (details)
						For a database query we will not know the number of rows
						So we need to use a foreach loop to create a row for each result
					*@
					@foreach(var territory in Model.TerritoryResults)
					{
						<tr>
							<td>@territory.TerritoryID</td>
							<td>@territory.TerritoryDescription</td>
							<td><select disabled="true">
								@foreach(var region in Model.RegionsList)
								{
									if(region.RegionID == territory.RegionID)
									{
										<option value="@region.RegionID" selected>@region.RegionDescription</option>
									}
									else
									{
										<option value="@region.RegionID">@region.RegionDescription</option>
									}
								}
								</select>
							</td>
						</tr>
					}
				</tbody>
				<tfoot>
					@*used for summary table display (Example totals) and also for Pagination*@
					<tr>
						<td colspan="3">
							@{
								if(Model.Pager != null)
								{
									foreach(var pageRef in Model.Pager)
									{
										if(pageRef == Model.Pager.CurrentPage)
										{
											<b>@pageRef.Text</b>
										}
										else
										{
											<a title="Page @pageRef.Page"
												asp-page="/Samples/PartialFilterSearch"
												asp-route-currentPage="@pageRef.Page"
												asp-route-partialSearchText="@Model.partialSearchText"
												asp-route-searchRegionID="@Model.searchRegionID">
												@pageRef.Text
											</a>
									
									
										}
									}
								}
							}
						</td>
					</tr>
				</tfoot>
			</table>
		}
	}
	else
	{
		<br />
	}
	<button type="submit" asp-page-handler="Clear">Clear</button>
</form>

ExampleWebApp/BobWebApp/Pages/Samples/ProductCRUD.cshtml
@page "{productID?}"
@model ExampleWebApp.Pages.Samples.ProductCRUDModel
@{
	ViewData["Title"] = "Product CRUD";
}

<h1>Product CRUD</h1>

@if (Model.HasFeedback)
{
	<p>@Model.Feedback</p>
}
@if(Model.HasError)
{
	<p>@Model.ErrorMessage</p>
}

<form method="post">
@* Setup the parts of the product *@

@*create a form control to hold the PK value
	This control should not be changable IF your PK is an IDENTITY
	this control CAN be visible (type="text") or hidden (type="hidden")
	visible or hidden depend on the design and business requirements.
*@
<label>
	Product ID:
	@if(Model.ProductInfo == null)
	{
			<input type="text" asp-for="ProductInfo.ProductID" readonly data-val="false" value="0"/>
		}
		else
		{
			<input type="text" asp-for="ProductInfo.ProductID" readonly data-val="false" />
		}
	</label>
<label>
	Product Name:
	<input type="text" asp-for="ProductInfo.ProductName" placeholder="product name" />
</label>
<label>
	Category:
	<select asp-for="ProductInfo.CategoryID">
		<option value="0">select...</option>
		@foreach(var category in Model.CategoryList)
		{
			<option value="@category.CategoryID"
				selected=@(Model.ProductInfo != null && category.CategoryID == Model.ProductInfo.CategoryID)>
				@category.CategoryName
			</option>
		}
	</select>
</label>
<label>
    Supplier:
    <select asp-for="ProductInfo.SupplierID">
		<option value="0">select...</option>
        @foreach(var item in Model.SupplierList)
        {
            <option value="@item.SupplierID" 
                selected=@(Model.ProductInfo != null && item.SupplierID == Model.ProductInfo.SupplierID)>
                @item.CompanyName
            </option>
        }
    </select>
</label>
<label>
	Unit Size:
	<input type="text" asp-for="ProductInfo.QuantityPerUnit" placeholder="unit size" />
</label>
<label>
	Min Order Qty:
	<input type="number" asp-for="ProductInfo.MinimumOrderQuantity" placeholder="minimum order qty"
		step="1" min="1" />
</label>
<label>
    Unit Price:
    <input type="number" asp-for="ProductInfo.UnitPrice" placeholder="unit price"
                step="0.01" min="0.00"/>
</label>
<label>
    Units on Order:
    <input type="text" asp-for="ProductInfo.UnitsOnOrder" placeholder="units on order"
        disabled="true"/>
</label>
@* for a bool we will use checkboxes, the default transfer of data for the checkbox is:
		not check = null
		check = on
	If using a checkbox for a boolean (true or false)
		set the attribute value="true" for the checkbox
*@
<label>
	Discontinued:&nbsp;
	<input type="checkbox" asp-for="ProductInfo.Discontinued" value="true" />
	&nbsp;&nbsp; (discontinued if checked)
</label>
<br /><br />
@* Manage the button to restrict user access
	Base this on if a Product was used to call the product.
*@
	@if (Model.ProductInfo != null)
	{
		<button type="submit" asp-page-handler="New" disabled>Save New</button>
		<button type="submit" asp-page-handler="Update">Update</button>
		<button type="submit" asp-page-handler="Delete" formnovalidate
			onclick="return confirm('Are you sure you wish to discontinue the product?')">
			Discontinue
		</button>
		<button type="submit" asp-page-handler="Clear" formnovalidate>Clear</button>
		<button type="submit" asp-page-handler="Search" formnovalidate>Search</button>
	}
	else
	{
		<button type="submit" asp-page-handler="New">Save New</button>
		<button type="submit" asp-page-handler="Update" disabled>Update</button>
		<button type="submit" asp-page-handler="Delete" formnovalidate disabled
			onclick="return confirm('Are you sure you wish to discontinue the product?')">
			Discontinue
		</button>
		<button type="submit" asp-page-handler="Clear" formnovalidate>Clear</button>
		<button type="submit" asp-page-handler="Search" formnovalidate>Search</button>
	}
</form>

ExampleWebApp/BobWebApp/Pages/Samples/Query.cshtml
@page 
@model ExampleWebApp.Pages.Samples.QueryModel
@{
	ViewData["Title"] = "Table Queries";
}

<h1>Partial String Query Resulting in a Table Display</h1>

<p>@Model.partialSearchFeedback</p>

<form method="post">
	<label>
		Enter a partial Territory description:
		<input type="text" asp-for="partialSearchText"
			placeholder="enter your search string" />
	</label>
	<button type="submit" asp-page-handler="Search">Search Territories</button>
	<br />
	<select asp-for="searchRegionID">
		<option value="0">select a region...</option>
		@foreach(var region in Model.RegionsList)
		{
		
			if(region.RegionID == Model.searchRegionID)
			{
				<option value="@region.RegionID" selected>@region.RegionDescription</option>
			}
			else
			{
				<option value="@region.RegionID">@region.RegionDescription</option>
			}
		}
	</select>
	<button type="submit" asp-page-handler="DDLSearch">Search Territories</button>
	<br />
	@if (!string.IsNullOrEmpty(Model.partialSearchText) || Model.searchRegionID >= 1)
	{
		if (Model.TerritoryResults.Count == 0)
		{
			<p style="color:deeppink; font-weight:bold; font-size:large;">
				There are no territories matching your search request.
			</p>
		}
		else 
		{
			<table>
				<thead>
					@*Used for the column titles*@
					<tr>
						<th>Territory ID</th>
						<th>Description</th>
						<th>Region ID</th>
					</tr>
				</thead>
				<tbody>
					@*Used for the table rows (details)
						For a database query we will not know the number of rows
						So we need to use a foreach loop to create a row for each result
					*@
					@foreach(var territory in Model.TerritoryResults)
					{
						<tr>
							<td>
								@*
									Will send the Territory ID to another page
									using the anchor tag and we MUST reference a page in 
									our pages folder
									We attach the value to the page reference in the anchor tag

								*@
								<a href="/Samples/ReceivingPage/@territory.TerritoryID">
									Edit Territory	
								</a>
								
							</td>
							<td>@territory.TerritoryDescription</td>
							<td><select disabled="true">
								@foreach(var region in Model.RegionsList)
								{
									if(region.RegionID == territory.RegionID)
									{
										<option value="@region.RegionID" selected>@region.RegionDescription</option>
									}
									else
									{
										<option value="@region.RegionID">@region.RegionDescription</option>
									}
								}
								</select>
							</td>
						</tr>
					}
				</tbody>
				<tfoot>
					@*used for summary table display (Example totals) and also for Pagination*@
					<tr>
						<td colspan="3">
							@{
								if(Model.Pager != null)
								{
									foreach(var pageRef in Model.Pager)
									{
										if(pageRef == Model.Pager.CurrentPage)
										{
											<b>@pageRef.Text</b>
										}
										else
										{
											<a title="Page @pageRef.Page"
												asp-page="/Samples/Query"
												asp-route-currentPage="@pageRef.Page"
												asp-route-partialSearchText="@Model.partialSearchText"
												asp-route-searchRegionID="@Model.searchRegionID">
												@pageRef.Text
											</a>
									
									
										}
									}
								}
							}
						</td>
					</tr>
				</tfoot>
			</table>
		}
	}
	else
	{
		<br />
	}
	<button type="submit" asp-page-handler="Clear">Clear</button>
</form>